"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Maxito7"
email = "max.jacinto@pucp.edu.pe"

[ui]
# Use Difftastic by default
diff-formatter = ["difft", "--color=always", "$left", "$right"]
editor = "nvim"
